include hyde.conf

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
allow_remote_control yes
background_opacity 0.8


map ctrl+shift+enter launch --cwd=current
map ctrl+shift+t new_tab_with_cwd

# Abrir o scrollback atual no Neovim para busca/cópia pesada
map ctrl+shift+h show_scrollback
scrollback_pager nvim -c "set signcolumn=no showtabline=0" -c "silent! %s/\u001b\[[0-9;]*m//g" -c "autocmd TermOpen * startinsert" -c "set buftype=nofile" -


# Navegação entre abas
map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab

# Ir para abas específicas (estilo navegador)
map ctrl+shift+1 goto_tab 1
map ctrl+shift+2 goto_tab 2
map ctrl+shift+3 goto_tab 3

# Fechar aba
map ctrl+shift+q close_tab

tab_bar_style        powerline
tab_powerline_style  slanted
tab_title_template   "{index}: {title}"
active_tab_font_style bold
inactive_tab_font_style normal

# remap to open new kitty tab in the same directory (default is home dir)
# map ctrl+shift+t            new_tab_with_cwd

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
# input_delay 0
# repaint_delay 2
# sync_to_monitor no
# wayland_enable_ime no
font_size 12
